### PR TITLE
Update to scala 2.11.7 and finagle 6.31.0

### PR DESCRIPTION
**Pull request by pimeys**
This version works with the most recent scala and finagle. I took an exaple from twitter's finagle-redis library and took their version of naggati\* to this project. Got it to work and all the tests are green. Are you still maintaining this library?
- https://github.com/twitter/finagle/tree/develop/finagle-redis/src/main/scala/com/twitter/finagle/redis/naggati

### CODE REVIEW

**Comment by cb372** [comment]
Wow, I never expected anyone to even find this project, let alone send a PR. Thanks for the interest!

Your changes look fine to me. Do you mind rebasing? Given that somebody other than me has started looking at the project, I decided to start cleaning things up, starting with adding a Travis build and getting rid of the old IDEA sbt plugin. Unfortunately this caused your PR to become unmergeable - sorry about that.

If you're interesting in using or contributing to this library, I can put some work into it, e.g adding a README, publishing to Maven Central, etc. Disclaimer: I have never used it in production - use at your own risk!

**Comment by pimeys** [comment]
I can do that when I get to work. We started to use finagle for some of our projects and we need an async beanstalkd client. Maybe I could write some documentation also...

**Comment by pimeys** [comment]
Oh btw, do you have a maven repo somewhere where you can publish the library? Now I'm running it from the `./lib` which is not that nice.

**Comment by cb372** [comment]
> do you have a maven repo somewhere

Yes, I can put it on Maven Central. I'll do the required sbt config after I merge your PR.

Sorry again about the rebase. I should have merged this before I started messing with anything.

**Comment by pimeys** [comment]
Rebased. Needed to update that sbt-idea to a newer version so I got the build to work.

**Comment by pimeys** [comment]
I added another commit here, which I don't want to port to the old code anymore. We use lots of tubes, so it's necessary to be able to put the messages into different tubes easily.

**Comment by cb372** [comment]
Thanks! Next steps are getting it onto Maven Central and adding a README. I'll do that tomorrow.

**Pull request merged**
